name: Install dependencies
description: Install Node and project dependencies using PNPM
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
    - name: Install PNPM
      run: npm i -g pnpm
      shell: bash
    - run: pnpm i --frozen-lockfile
      shell: bash